/* tslint:disable */
/* eslint-disable */
/**
 * Lumea API
 * # Lumea Interior Layout Generator API  Advanced AI-powered interior layout generator with explainable spatial reasoning.  ## Features - **3D Scene Management**: Create and manage complex 3D interior layouts - **Asset Processing Pipeline**: Automatic optimization with KTX2, Draco, and Meshopt variants - **Real-time Collaboration**: Server-Sent Events for live scene updates - **Optimistic Locking**: If-Match headers for safe concurrent editing - **Category-based Organization**: Enhanced scene manifests with filtering capabilities - **Processing Queue**: Background asset processing with status tracking  ## Authentication All endpoints require Bearer token authentication unless explicitly marked as public.  ## Rate Limiting - General API: 100 requests per 15 minutes per IP - Authentication: 5 attempts per 15 minutes per IP  ## Versioning Scene operations support optimistic locking via If-Match headers for safe concurrent editing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lumea.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssetDownloadInfo } from './asset-download-info';

/**
 * 
 * @export
 * @interface BatchDownloadResponse
 */
export interface BatchDownloadResponse {
    /**
     * Scene ID
     * @type {string}
     * @memberof BatchDownloadResponse
     */
    'sceneId': string;
    /**
     * Scene name
     * @type {string}
     * @memberof BatchDownloadResponse
     */
    'sceneName': string;
    /**
     * Assets available for download
     * @type {Array<AssetDownloadInfo>}
     * @memberof BatchDownloadResponse
     */
    'assets': Array<AssetDownloadInfo>;
    /**
     * Total file size in bytes
     * @type {number}
     * @memberof BatchDownloadResponse
     */
    'totalSize': number;
    /**
     * Number of assets
     * @type {number}
     * @memberof BatchDownloadResponse
     */
    'assetCount': number;
    /**
     * Batch generation timestamp
     * @type {string}
     * @memberof BatchDownloadResponse
     */
    'generatedAt': string;
}

