/* tslint:disable */
/* eslint-disable */
/**
 * Lumea API
 * # Lumea Interior Layout Generator API  Advanced AI-powered interior layout generator with explainable spatial reasoning.  ## Features - **3D Scene Management**: Create and manage complex 3D interior layouts - **Asset Processing Pipeline**: Automatic optimization with KTX2, Draco, and Meshopt variants - **Real-time Collaboration**: Server-Sent Events for live scene updates - **Optimistic Locking**: If-Match headers for safe concurrent editing - **Category-based Organization**: Enhanced scene manifests with filtering capabilities - **Processing Queue**: Background asset processing with status tracking  ## Authentication All endpoints require Bearer token authentication unless explicitly marked as public.  ## Rate Limiting - General API: 100 requests per 15 minutes per IP - Authentication: 5 attempts per 15 minutes per IP  ## Versioning Scene operations support optimistic locking via If-Match headers for safe concurrent editing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lumea.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateSceneItemDto
 */
export interface UpdateSceneItemDto {
    /**
     * Category key referencing project assets
     * @type {string}
     * @memberof UpdateSceneItemDto
     */
    'categoryKey'?: string;
    /**
     * Optional model identifier within category
     * @type {string}
     * @memberof UpdateSceneItemDto
     */
    'model'?: string;
    /**
     * Position X coordinate
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'positionX'?: number;
    /**
     * Position Y coordinate
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'positionY'?: number;
    /**
     * Position Z coordinate
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'positionZ'?: number;
    /**
     * Rotation X (pitch) in degrees
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'rotationX'?: number;
    /**
     * Rotation Y (yaw) in degrees
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'rotationY'?: number;
    /**
     * Rotation Z (roll) in degrees
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'rotationZ'?: number;
    /**
     * Scale X factor
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'scaleX'?: number;
    /**
     * Scale Y factor
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'scaleY'?: number;
    /**
     * Scale Z factor
     * @type {number}
     * @memberof UpdateSceneItemDto
     */
    'scaleZ'?: number;
    /**
     * Material variant identifier
     * @type {string}
     * @memberof UpdateSceneItemDto
     */
    'materialVariant'?: string;
    /**
     * Whether the item can be selected
     * @type {boolean}
     * @memberof UpdateSceneItemDto
     */
    'selectable'?: boolean;
    /**
     * Whether the item is locked from editing
     * @type {boolean}
     * @memberof UpdateSceneItemDto
     */
    'locked'?: boolean;
    /**
     * Additional metadata as JSON
     * @type {object}
     * @memberof UpdateSceneItemDto
     */
    'meta'?: object;
    /**
     * Material property overrides as JSON
     * @type {object}
     * @memberof UpdateSceneItemDto
     */
    'materialOverrides'?: object;
}

