name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '10'

      - name: Update Node.js dependencies
        run: |
          # Update all dependencies
          pnpm update --latest
          
          # Check for outdated packages
          pnpm outdated || true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Update Python dependencies (Solver)
        working-directory: apps/solver
        run: |
          # Check if requirements files exist before updating
          if [ -f "requirements.txt" ]; then
            echo "Found requirements.txt, checking for updates..."
            pip install --upgrade pip
            pip list --outdated || true
          else
            echo "No requirements.txt found, skipping Python dependency updates"
          fi
        continue-on-error: true

      - name: Run tests
        run: |
          pnpm install
          pnpm test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Automated Dependency Updates'
          body: |
            This is an automated PR to update project dependencies.
            
            ## Changes
            - Updated Node.js packages to latest versions
            - Updated Python packages to latest versions
            
            ## Testing
            - [x] All tests pass
            - [x] Build verification successful
            
            Please review the changes and merge if everything looks good.
          branch: chore/dependency-updates
          delete-branch: true