name: Test Registry Connection

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-registry:
    name: Test Container Registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Test registry authentication
        run: |
          echo "Testing Docker Hub connection..."
          echo "Registry: ${{ secrets.CONTAINER_REGISTRY }}"
          echo "Username: ${{ secrets.REGISTRY_USERNAME }}"
          echo "Token configured: ${{ secrets.REGISTRY_PASSWORD != '' }}"
          echo "Expected format:"
          echo "  Registry: docker.io"
          echo "  Username: your-dockerhub-username"
          echo "  Token: dckr_pat_xxxxxxxxxx"
          
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Test simple push
        run: |
          # Create a minimal test image
          echo "FROM alpine:latest" > Dockerfile
          echo "RUN echo 'Hello World'" >> Dockerfile
          
          # Build and push test image
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/test:latest .
          docker push ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/test:latest
          
          echo "✅ Registry connection successful!"
          
      - name: Cleanup test image
        run: |
          echo "Test completed - you can delete the test image from your registry if desired"